### ISSUE TITLE
Please Update to 1.20.1!!

### ISSUE THREAD

**Issue by allusive-dev** [NyCodeGHG/no-lan-cheating#12]
This is a amazing mod which has saved me many times and is super useful so please update it!

I'm a Mod Developer myself but I tried to implement it in a 1.20 mod and got caught on a ton of odd errors. 

But yeah please update this awesome mod!

**Comment by NyCodeGHG** [comment]
i'll see if i can find some time to update it :)

**Comment by NyCodeGHG** [comment]
updated to 1.20.1
